spring:
  profiles:
    active: dev
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://localhost:5432/xxx
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE-DATES-AS-TIMESTAMPS: false
  liquibase:
    enabled: true
  data:
    mongodb:
      uri: ${mongodb-uri}
      database: products-db
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-user}
    password: ${mail-pass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  info:
    address: Dnipro, Office 10
    phone: 01329129312

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

jwt:
  secret: super-long-HARD-work-to-be-used-for_SECRET_123
  access-token:
    ttl-millis: 60000
  refresh-token:
    ttl-millis: 60000